import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "@/components/layout";
import { ThemeProvider } from "next-themes";
import { LangProvider } from "@/components/providers/LanguageProvider";
import { getAllDictionaries } from "@/lib/dictionaries";
import { headers } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const dictionaries = await getAllDictionaries()
  const _headers = await headers()
  const locale = _headers.get("accept-language")??"fr-FR"

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <MainLayout>
          <ThemeProvider attribute={'class'} defaultTheme="system">
            <LangProvider dictionaries={dictionaries} locale={locale}>
              {children}
            </LangProvider>
          </ThemeProvider>
        </MainLayout>
      </body>
    </html>
  );
}
